BadWolf1023/MKW-Table-Bot

BadWolfBot.py, ErrorChecker.py, Race.py, Room.py, WiimfiSiteFunctions.py, commands.py, common.py, testing_rooms/removerace_one.html, testing_rooms/removerace_two.html
Fixed numerous bugs, restructured Rooms, remove race now works properly
=> Stable race removal

Lounge.py, MogiUpdate.py, WiimmfiSiteFunctions.py, commands.py, common.py
Reporter+ will now receiving warnings if they take an approve/deny action on a table that has already been approved/denied
Additionally, Table Bot will warn Reporter+ if an exact duplicate was submitted by someone through ?rtupdate/?ctupdate
=> Lounge submissions redundancy checks

MiiPuller.py, common.py
=> Miis fixed

BadWolfBot.py, TableBotExceptions.py, commands.py, common.py, data_tracking/DataTracker.py, data_tracking/Data_Tracker_SQL_Query_Builder.py, data_tracking/database_maintenance.sql
=> Meta Commands: ?populartracks and ?unpopulartracks

AbuseTracking.py, BadWolfBot.py, commands.py
Abuse report messages in the #bot-abuse-report channel are now embeds:
=> More readable Bot Abuse Reports

BadWolfBot.py, TableBotExceptions.py, URLCacher.py, WiimmfiSiteFunctions.py
=> Remove MKWX Multithreaded GUI related code

TableBot.py
Merge room command was adding modified races to the database, critical bug
=> Merge room command was adding tabler modified races to the database

BadWolfBot.py, InteractionUtils.py, Mii.py, MiiPuller.py, SmartTypes.py, TableBot.py, commands.py, slash_cogs/MiscSlashCommands.py
=> Page Command + Bug Fixes

Components.py, slash_cogs/LoungeSlashCommands.py
=> fix misspelling

Room.py
**Error:**
Table Bot tries to change a position that doesn't exist - a manual DC placement that existed before but was edited and no longer exists in `apply_tabler_adjustments()`.
**Reproduction steps:**
- set player who is missing to "on results" and add their placement to a race
- change their position
- set the same player to "not on results" (remove their manual DC placement from the race)
- IndexError raised
This error occurs because DC placements are handled *before* placement changes. So it kind of creates a race condition - the placement might've existed before when you edited the position, but when you `apply_tabler_adjustments()` the manual DC placement no longer exists.
Handling manual DC placements and positions changes in the same step fixes this issue. Manual DC placements …
=> manual DC placements patch

ScoreKeeper.py, War.py
Fixes bugs relating to API.
Current fixes:
=> FFA tag patch

api/api_data_builder.py, api/css/full_scores_neon.css, api/css/full_scores_orange.css, api/css/full_scores_pastel.css, api/css/full_scores_vertical_blue.css, api/endpoints.py
=> Api patches

War.py, api/api_common.py, api/api_data_builder.py, api/endpoints.py, api/html/picture_builder.html, api/token.py, commands.py
Picture endpoint for API + JSON endpoint for last discord picture URL
=> Picture endpoint for API + JSON endpoint for last discord picture URL

BadWolfBot.py, MogiUpdate.py, commands.py
Automatically update tier data and channels. No hard coded tier numbers and MMR cutoffs.
=> Automated mogi update tier changes

AbuseTracking.py, BadWolfBot.py, Components.py, InteractionUtils.py, ScoreKeeper.py, ServerFunctions.py, UtilityFunctions.py, api/api_channelbot_interface.py, commands.py, common.py, slash_cogs/AdminSlashCommands.py, slash_cogs/LoungeSlashCommands.py, slash_cogs/MiscSlashCommands.py, slash_cogs/PrivateSlashCommands.py, slash_cogs/StatisticsSlashCommands.py, slash_cogs/TablingSlashCommands.py
- Changed slash command permissions to comply with permissions v2
- Updated `?copyfrom` so that guild arg is no longer necessary
- Fixed war format bug in `?sw`
- Fixed bug in `InteractionUtils.build_mentions()`
- Fixed race condition/timeout bug with the submission button
- Added 5 second user cooldown for `?mii` command
- Removed use of abuse tracking system
=> Multiple additions and fixes

BadWolfBot.py, Room.py, TableBot.py, commands.py, common.py
- ?rxx now displays the Table ID, used for the API
- ?TableID, displays the Table ID in plain text, so it is easy to copy on mobile.
- Fixed bug where table bot crashes when you remove all races (Basically I just didnt let them remove all races)
=> Bug fixes and slight QoL changes for API Users

BadWolfBot.py, Components.py, commands.py
Left out an `await` for async function.
=> Quick bug fix

BadWolfBot.py, CHANGELOG.md, ComponentPaginator.py, slash_cogs/TablingSlashCommands.py
=> Paginator bug hotfix and `/tableid` slash command

BadWolfBot.py, ComponentPaginator.py, InteractionUtils.py, commands.py, slash_cogs/StatisticsSlashCommands.py, slash_cogs/TablingSlashCommands.py
=> Mass information send out + Pagination ApplicationContext bug fix

slash_cogs/TablingSlashCommands.py
=> Fix /predict bug

BadWolfBot.py, commands.py
This is a command that can edit the an entire GP for all players, it helps with efficiency and most importantly, the least amount of pings of Table Bot (especially useful in lounge as it has mention cooldowns.)
=> New Command - /fulledit

slash_cogs/TablingSlashCommands.py
The title. I could not test this, slash commands wouldn't show.
Should work, but please test.
=> Added slash command for /fulledit

commands.py, slash_cogs/TablingSlashCommands.py
=> Rewording and grammar correction

Components.py, InteractionUtils.py
=> Fix member/user bug with MessageWrapper

InteractionUtils.py
=> fix member bug

InteractionUtils.py
=> fix author of MessageWrapper

ErrorChecker.py, InteractionUtils.py
=> Fix DC error footer text

commands.py
=> fix lorenzi edit link shortening in `wp` embed

BadWolfBot.py, URLShortener.py, commands.py
`private.txt` needs to be edited--add line for TinyURL token after the Bitly token and before the Lounge token.
=> TinyURL endpoint for Lorenzi link shortening

BadWolfBot.py, Components.py, ImageCombine.py, Mii.py, Player.py, Room.py, War.py, commands.py
- Added new command `?api`
- Provides links to the API for current table  
- Fixed removal of `Update` button after tables are submitted
- Fixed changed Mii names on footer of table picture
- Fixed save state issues with `War.manualEdits` (needs to be deep copied not shallow copied)
- Fixed bug with +- editing (and refactored `War.manualEdits` to make it easier)
- `War.manualEdits` is now `dict[FC, dict[gpNum, edit]]` instead of `dict[FC, list[tuple[gpNum, edit]]]` 
- Fixed bug with embed footer lengths
=> `?api` command and bug fixes

commands.py
Fixes a bug that occurs when a player has no previous miis
=> Bug fix when no previous miis are found

BadWolfBot.py, Components.py, Mii.py, Placement.py, Player.py, Room.py, UserDataProcessing.py, commands.py, common.py, slash_cogs/MiscSlashCommands.py, slash_cogs/TablingSlashCommands.py
- New command `?changeraceorder [raceNum 1] [raceNum 2] ...`
- Fix `?vr` command permissions and refreshing bugs
- Fix table picture footer mii names bug
=> Various bug fixes + `?changeraceorder`

Room.py, commands.py
=> fix `/changeraceorder`

InteractionUtils.py, MogiUpdate.py, Placement.py, Race.py, Room.py, Stats.py, common.py, slash_cogs/LoungeSlashCommands.py
- fix /update modal bug
- fix CT summary channel names bug
- make Race.addPlacement() more efficient (just because)
=> Bug fixes 

BadWolfBot.py, CHANGELOG.md, Components.py, ImageCombine.py, MiiPuller.py, MogiUpdate.py, Room.py, Stats.py, War.py, api/api_data_builder.py, api/css/full_scores_base.css, api/css/full_scores_orange_discord.css, commands.py, common.py
- Fix Lounge update JSON data bug
- The "tier" value needs to begin with the word "Tier"
- fix `/changeraceorder` so that race edits follow race order changes
- MII_CACHE fix? (not sure if this is a contribution to memory issues, but seems like it holds on to unnecessary records that could be removed)
- There's also an issue with the backup picture generation - html2image isn't downloading the file to the right location, and I've no idea where the files could be downloading to
=> Some updates

WiimmfiParser.py
=> fix race CT check?

Race.py, Room.py
=> Fix sub updates for ?changeraceorder and update CTGP region

Room.py, commands.py
=> display warning for race edits

InteractionUtils.py
=> update proxy message __str__()

BadWolfBot.py, Race.py, War.py, WiimmfiSiteFunctions.py, commands.py, common.py
=> Update CTGP region validation

WiimmfiSiteFunctions.py, commands.py
=> fix ctww command bug

BadWolfBot.py, ComponentPaginator.py, Components.py, InteractionUtils.py, War.py, commands.py, slash_cogs/LoungeSlashCommands.py, slash_cogs/TablingSlashCommands.py
=> add tag change functionality

Components.py
=> fix some bugs with `edittag`

ImageCombine.py, MogiUpdate.py, Room.py, SmartTypes.py, TimerDebuggers.py, api/api_data_builder.py, commands.py, data_tracking/DataTracker.py, data_tracking/Data_Tracker_SQL_Query_Builder.py, slash_cogs/StatisticsSlashCommands.py
- separates RT and CT record in output
- added ability to compare records of 2 other players
- fix #199
- fix #196
=> RT + CT for record command + bug fixes

UtilityFunctions.py
Untested in actual environment, there is no reason it wouldnt work though.
=> Added 8 digit rxx and race ID functionality

api/api_data_builder.py, commands.py
=> fix for html2image

BadWolfBot.py
=> fix bot status
